import { TypeformTemplate } from './typeformTemplates';

/**
 * Templates brandés avec des layouts vraiment originaux
 * Inspirés des grandes marques mais avec des designs uniques
 */

export const brandedTemplates: TypeformTemplate[] = [
  // Template 1: Style magazine moderne (asymétrique)
  {
    id: 'branded-magazine-style',
    name: 'Magazine Premium',
    description: 'Design éditorial moderne avec typographie audacieuse',
    category: 'lead-generation',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    theme: {
      backgroundColor: '#1A1A1A',
      textColor: '#FFFFFF',
      primaryColor: '#FF6B35',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Discover Your Perfect Match',
        description: 'A personalized experience awaits',
        required: false,
        placeholder: '',
        layout: 'magazine-style',
        imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80',
        backgroundType: 'image',
        backgroundImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1920&q=80',
        backgroundOverlayOpacity: 0.7,
        backgroundOverlayColor: '#1A1A1A',
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: 'So we can personalize your experience',
        required: true,
        placeholder: 'Type your name...',
        layout: 'asymmetric-left',
        backgroundType: 'color',
        panelBackgroundColor: '#2D2D2D',
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Your email address',
        description: 'We respect your privacy',
        required: true,
        placeholder: 'you@example.com',
        layout: 'asymmetric-right',
        backgroundType: 'color',
        panelBackgroundColor: '#FF6B35',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'What brings you here today?',
        description: 'Select your primary interest',
        required: true,
        options: ['Personal Growth', 'Career Development', 'Lifestyle Change', 'Exploration'],
        layout: 'cards-large',
        backgroundType: 'color',
        panelBackgroundColor: '#1A1A1A',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Welcome Aboard',
        description: 'Your journey starts now',
        required: false,
        placeholder: '',
        layout: 'magazine-style',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FF6B35 0%, #1A1A1A 100%)',
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
    ],
  },

  // Template 2: Style minimal luxe (floating cards)
  {
    id: 'branded-minimal-luxury',
    name: 'Minimal Luxe',
    description: 'Élégance minimaliste avec cards flottantes',
    category: 'lead-generation',
    thumbnail: 'https://images.unsplash.com/photo-1600950207944-0d63e8edbc3f?w=800&q=80',
    theme: {
      backgroundColor: '#F5F5F0',
      textColor: '#2C2C2C',
      primaryColor: '#8B7355',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Timeless Elegance',
        description: 'Begin your curated experience',
        required: false,
        placeholder: '',
        layout: 'floating-card',
        imageUrl: 'https://images.unsplash.com/photo-1600950207944-0d63e8edbc3f?w=1200&q=80',
        backgroundType: 'color',
        panelBackgroundColor: '#F5F5F0',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'xlarge',
        textColor: '#2C2C2C',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your name',
        description: '',
        required: true,
        placeholder: 'Enter your name',
        layout: 'floating-card',
        backgroundType: 'color',
        panelBackgroundColor: '#FFFFFF',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        textColor: '#2C2C2C',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email address',
        description: '',
        required: true,
        placeholder: 'your@email.com',
        layout: 'floating-card',
        backgroundType: 'color',
        panelBackgroundColor: '#8B7355',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Your preference',
        description: 'Choose what resonates with you',
        required: true,
        options: ['Classic', 'Modern', 'Eclectic', 'Minimalist'],
        layout: 'cards-minimal',
        backgroundType: 'color',
        panelBackgroundColor: '#F5F5F0',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        textColor: '#2C2C2C',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Exquisite Choice',
        description: 'We look forward to serving you',
        required: false,
        placeholder: '',
        layout: 'floating-card',
        backgroundType: 'color',
        panelBackgroundColor: '#F5F5F0',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'xlarge',
        textColor: '#2C2C2C',
      },
    ],
  },

  // Template 3: Style tech moderne (side panel)
  {
    id: 'branded-tech-modern',
    name: 'Tech Forward',
    description: 'Design moderne avec panneau latéral innovant',
    category: 'saas',
    thumbnail: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=800&q=80',
    theme: {
      backgroundColor: '#0F0F1E',
      textColor: '#FFFFFF',
      primaryColor: '#6366F1',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Welcome to the Future',
        description: 'Powered by innovation',
        required: false,
        placeholder: '',
        layout: 'side-panel-left',
        imageUrl: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&q=80',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0F0F1E 0%, #1E1E3F 50%, #6366F1 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What should we call you?",
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'side-panel-right',
        backgroundType: 'color',
        panelBackgroundColor: '#1E1E3F',
        fontFamily: 'Inter',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Work email',
        description: 'For your personalized dashboard',
        required: true,
        placeholder: 'you@company.com',
        layout: 'side-panel-left',
        backgroundType: 'color',
        panelBackgroundColor: '#6366F1',
        fontFamily: 'Inter',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q3',
        type: 'choice',
        text: "What's your role?",
        description: 'Help us customize your experience',
        required: true,
        options: ['Developer', 'Designer', 'Product Manager', 'Founder', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#0F0F1E',
        fontFamily: 'Inter',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'All Set!',
        description: "Let's build something amazing",
        required: false,
        placeholder: '',
        layout: 'side-panel-right',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0F0F1E 0%, #6366F1 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
    ],
  },

  // Template 4: Style organic/naturel (fullscreen split)
  {
    id: 'branded-organic-nature',
    name: 'Organic Essence',
    description: 'Design naturel avec split screen immersif',
    category: 'wellness',
    thumbnail: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&q=80',
    theme: {
      backgroundColor: '#E8DCC4',
      textColor: '#3D3D3D',
      primaryColor: '#6B8E23',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Embrace Natural Wellness',
        description: 'Your journey to balance begins here',
        required: false,
        placeholder: '',
        layout: 'fullscreen-split',
        imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1200&q=80',
        backgroundType: 'image',
        backgroundImage: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1920&q=80',
        backgroundOverlayOpacity: 0.3,
        backgroundOverlayColor: '#E8DCC4',
        fontFamily: 'Lora',
        fontSize: 'xlarge',
        textColor: '#3D3D3D',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: "Let us know who we're welcoming",
        required: true,
        placeholder: 'Your name',
        layout: 'compact-inline',
        backgroundType: 'color',
        panelBackgroundColor: '#F5EDD6',
        fontFamily: 'Lora',
        fontSize: 'large',
        textColor: '#3D3D3D',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email',
        description: 'For your wellness updates',
        required: true,
        placeholder: 'you@example.com',
        layout: 'compact-inline',
        backgroundType: 'color',
        panelBackgroundColor: '#6B8E23',
        fontFamily: 'Lora',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q3',
        type: 'choice',
        text: "What's your focus?",
        description: 'Select your wellness priority',
        required: true,
        options: ['Mind', 'Body', 'Spirit', 'Balance'],
        layout: 'cards-large',
        backgroundType: 'color',
        panelBackgroundColor: '#E8DCC4',
        fontFamily: 'Lora',
        fontSize: 'large',
        textColor: '#3D3D3D',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Namaste',
        description: 'Your wellness journey awaits',
        required: false,
        placeholder: '',
        layout: 'fullscreen-split',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #E8DCC4 0%, #6B8E23 100%)',
        fontFamily: 'Lora',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
    ],
  },

  // Template 5: Style bold/vibrant (minimal center avec interactions fortes)
  {
    id: 'branded-bold-vibrant',
    name: 'Bold & Vibrant',
    description: 'Énergie pure avec design audacieux',
    category: 'fitness',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    theme: {
      backgroundColor: '#FF4757',
      textColor: '#FFFFFF',
      primaryColor: '#2ED573',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'GET PUMPED!',
        description: 'Your transformation starts NOW',
        required: false,
        placeholder: '',
        layout: 'minimal-center',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FF4757 0%, #FF6B81 50%, #2ED573 100%)',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name, champion?",
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'minimal-center',
        backgroundType: 'color',
        panelBackgroundColor: '#FF6B81',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email for your progress tracker',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'minimal-center',
        backgroundType: 'color',
        panelBackgroundColor: '#2ED573',
        fontFamily: 'Montserrat',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'q3',
        type: 'choice',
        text: "What's your fitness goal?",
        description: 'Choose ONE primary goal',
        required: true,
        options: ['Build Muscle', 'Lose Weight', 'Get Flexible', 'Boost Energy'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#FF4757',
        fontFamily: 'Montserrat',
        fontSize: 'large',
        textColor: '#FFFFFF',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "LET'S DO THIS! 💪",
        description: 'Your journey to greatness begins',
        required: false,
        placeholder: '',
        layout: 'minimal-center',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #2ED573 0%, #FF4757 100%)',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
    ],
  },
];
