import { TypeformQuestion } from '../components/TypeformPreview';

export interface TypeformTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  questions: TypeformQuestion[];
  theme?: {
    backgroundColor?: string;
    textColor?: string;
    primaryColor?: string;
  };
}

const typeformTemplatesRaw: TypeformTemplate[] = [
  // ===== FEEDBACK & SATISFACTION =====
  {
    id: 'customer-feedback',
    name: 'Customer Feedback',
    description: 'Collect valuable feedback from your customers',
    category: 'feedback',
    thumbnail: 'https://images.typeform.com/images/vZe5UPd5c9kN/image/default',
    theme: {
      backgroundColor: '#5C3D2E',
      textColor: '#FFFFFF',
      primaryColor: '#D4A574',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'We Value Your Feedback',
        description: 'Help us serve you better',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=800&q=80',
        panelBackgroundColor: '#5C3D2E',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5C3D2E 0%, #8B6F47 50%, #D4A574 100%)',
        backgroundOverlayOpacity: 0.2,
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: '',
        required: true,
        placeholder: 'Jane Doe',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#8B6F47',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#FFF8E7',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: "We'll send you a summary",
        required: true,
        placeholder: 'jane@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#D4A574',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#3D2817',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How satisfied are you overall?',
        description: 'Not satisfied | Neutral | Very satisfied',
        required: true,
        min: 0,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        panelBackgroundColor: '#5C3D2E',
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
        textColor: '#FFFFFF',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Would you recommend us?',
        description: 'Select one',
        required: true,
        options: ['Definitely not', 'Probably not', 'Maybe', 'Probably', 'Definitely'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#8B6F47',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#FFF8E7',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'What can we improve?',
        description: 'Your honest feedback helps us grow',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#D4A574',
        fontFamily: 'Playfair Display',
        fontSize: 'large',
        textColor: '#3D2817',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you! 🙏',
        description: 'Your feedback matters to us',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5C3D2E 0%, #8B6F47 50%, #D4A574 100%)',
        fontFamily: 'Playfair Display',
        fontSize: 'xlarge',
      },
    ],
  },

  // Apple-inspired (Minimalist Black/White/Grey)
  {
    id: 'nps-survey',
    name: 'Net Promoter Score',
    description: 'Measure customer loyalty with NPS',
    category: 'feedback',
    theme: {
      backgroundColor: '#000000',
      textColor: '#FFFFFF',
      primaryColor: '#1D1D1F',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'How likely are you to recommend us?',
        description: 'Your opinion matters',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #1D1D1F 50%, #424245 100%)',
        fontFamily: 'SF Pro Display',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'scale',
        text: 'On a scale from 0 to 10, how likely are you to recommend us to a friend or colleague?',
        description: 'Not at all likely | Extremely likely',
        required: true,
        min: 0,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        panelBackgroundColor: '#1D1D1F',
        fontFamily: 'SF Pro Text',
        fontSize: 'large',
        textColor: '#F5F5F7',
      },
      {
        id: 'q2',
        type: 'long-text',
        text: 'What is the main reason for your score?',
        description: 'Please tell us more',
        required: true,
        placeholder: 'Type your answer here...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#424245',
        fontFamily: 'SF Pro Text',
        fontSize: 'large',
        textColor: '#F5F5F7',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you.',
        description: 'We appreciate your time.',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #1D1D1F 50%, #424245 100%)',
        fontFamily: 'SF Pro Display',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== LEAD GENERATION =====
  
  // Airbnb-inspired (Warm Pink/Red/Coral)
  {
    id: 'lead-gen-real-estate',
    name: 'Property Interest Form',
    description: 'Capture leads for real estate listings',
    category: 'lead-generation',
    theme: {
      backgroundColor: '#FF385C',
      textColor: '#FFFFFF',
      primaryColor: '#E61E4D',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Find Your Dream Home',
        description: 'Let us help you discover the perfect property',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        panelBackgroundColor: '#FF385C',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FF385C 0%, #E61E4D 50%, #BD1E59 100%)',
        fontFamily: 'Circular',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#E61E4D',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: "We'll send you matching properties",
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#BD1E59',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'What type of property are you looking for?',
        description: 'Select one',
        required: true,
        options: ['Apartment', 'House', 'Condo', 'Villa', 'Studio'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#FF385C',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'What is your budget range?',
        description: '',
        required: true,
        options: ['Under $300k', '$300k - $500k', '$500k - $1M', 'Over $1M'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#E61E4D',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'phone',
        text: 'Phone number (optional)',
        description: 'For faster communication',
        required: false,
        placeholder: '+1 (555) 000-0000',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#BD1E59',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "We'll be in touch soon! 🏡",
        description: 'Our team will contact you within 24 hours',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FF385C 0%, #E61E4D 50%, #BD1E59 100%)',
        fontFamily: 'Circular',
        fontSize: 'xlarge',
      },
    ],
  },

  // Spotify-inspired (Dark Green/Lime/Black)
  {
    id: 'newsletter-signup',
    name: 'Newsletter Signup',
    description: 'Grow your email list with style',
    category: 'lead-generation',
    theme: {
      backgroundColor: '#121212',
      textColor: '#FFFFFF',
      primaryColor: '#1DB954',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Stay in the Loop',
        description: 'Join thousands getting our weekly insights',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #121212 0%, #1DB954 100%)',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your first name?",
        description: 'So we can personalize your emails',
        required: true,
        placeholder: 'Alex',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#1DB954',
        fontFamily: 'Montserrat',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email address?",
        description: '',
        required: true,
        placeholder: 'alex@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#121212',
        fontFamily: 'Montserrat',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'multiple',
        text: 'What interests you?',
        description: 'Select all that apply',
        required: true,
        options: ['Tech News', 'Product Updates', 'Industry Insights', 'Case Studies', 'Events'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#178A42',
        fontFamily: 'Montserrat',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "You're on the list! 🎉",
        description: 'Check your inbox for a welcome email',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #121212 0%, #1DB954 100%)',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== CONTACT FORMS =====
  
  // Stripe-inspired (Purple/Blue/Indigo)
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Simple and elegant contact form',
    category: 'contact',
    theme: {
      backgroundColor: '#0A2540',
      textColor: '#FFFFFF',
      primaryColor: '#635BFF',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Get in Touch',
        description: "We'd love to hear from you",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0A2540 0%, #1E3A5F 50%, #635BFF 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: '',
        required: true,
        placeholder: 'John Doe',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#1E3A5F',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: '',
        required: true,
        placeholder: 'john@company.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#635BFF',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'How can we help?',
        description: '',
        required: true,
        options: ['Sales inquiry', 'Technical support', 'Partnership', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#0A2540',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'long-text',
        text: 'Tell us more',
        description: '',
        required: true,
        placeholder: 'Describe your needs...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#1E3A5F',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "We'll be in touch! ✉️",
        description: 'Expect a response within 24 hours',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0A2540 0%, #1E3A5F 50%, #635BFF 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // Notion-inspired (Beige/Brown/Cream)
  {
    id: 'support-request',
    name: 'Support Request',
    description: 'Help your customers get support quickly',
    category: 'contact',
    theme: {
      backgroundColor: '#F7F6F3',
      textColor: '#37352F',
      primaryColor: '#E9E7DD',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'How can we help?',
        description: "We're here to assist you",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #F7F6F3 0%, #E9E7DD 50%, #D4C5B0 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'email',
        text: "What's your email?",
        description: "We'll send updates to this address",
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#E9E7DD',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'choice',
        text: 'What type of issue are you experiencing?',
        description: '',
        required: true,
        options: ['Technical problem', 'Billing question', 'Feature request', 'Account issue', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#D4C5B0',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'How urgent is this?',
        description: '',
        required: true,
        options: ['Low - Can wait', 'Medium - Soon', 'High - ASAP', 'Critical - Blocking work'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#F7F6F3',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'long-text',
        text: 'Describe your issue',
        description: 'The more details, the better we can help',
        required: true,
        placeholder: 'Tell us what happened...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#E9E7DD',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Ticket created! 🎫',
        description: "We'll get back to you soon",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #F7F6F3 0%, #E9E7DD 50%, #D4C5B0 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== SURVEYS & RESEARCH =====
  
  // Netflix-inspired (Red/Black/Grey)
  {
    id: 'product-survey',
    name: 'Product Survey',
    description: 'Gather insights about your product',
    category: 'survey',
    theme: {
      backgroundColor: '#141414',
      textColor: '#FFFFFF',
      primaryColor: '#E50914',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Share Your Experience',
        description: 'Your feedback shapes our product',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
        panelBackgroundColor: '#141414',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #141414 0%, #E50914 100%)',
        fontFamily: 'Netflix Sans',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'choice',
        text: 'Which product did you use?',
        description: '',
        required: true,
        options: ['Product A', 'Product B', 'Product C', 'Product D'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#E50914',
        fontFamily: 'Netflix Sans',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'scale',
        text: 'How would you rate the quality?',
        description: 'Poor | Average | Excellent',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        panelBackgroundColor: '#141414',
        fontFamily: 'Netflix Sans',
        fontSize: 'xlarge',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How likely are you to use it again?',
        description: 'Very unlikely | Neutral | Very likely',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        panelBackgroundColor: '#B20710',
        fontFamily: 'Netflix Sans',
        fontSize: 'xlarge',
      },
      {
        id: 'q4',
        type: 'multiple',
        text: 'What did you like most?',
        description: 'Select all that apply',
        required: false,
        options: ['Easy to use', 'Great design', 'Fast performance', 'Good value', 'Reliable'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#E50914',
        fontFamily: 'Netflix Sans',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Any suggestions for improvement?',
        description: '',
        required: false,
        placeholder: 'Share your ideas...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#141414',
        fontFamily: 'Netflix Sans',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you! 🎬',
        description: 'Your feedback helps us improve',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #141414 0%, #E50914 100%)',
        fontFamily: 'Netflix Sans',
        fontSize: 'xlarge',
      },
    ],
  },

  // Tesla-inspired (Dark Grey/Red/White)
  {
    id: 'market-research',
    name: 'Market Research',
    description: 'Understand your market better',
    category: 'survey',
    theme: {
      backgroundColor: '#181B21',
      textColor: '#FFFFFF',
      primaryColor: '#CC0000',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Market Research Survey',
        description: 'Help us understand your needs',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #181B21 0%, #393C41 50%, #CC0000 100%)',
        fontFamily: 'Gotham',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'choice',
        text: 'What industry are you in?',
        description: '',
        required: true,
        options: ['Technology', 'Healthcare', 'Finance', 'Retail', 'Manufacturing', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#393C41',
        fontFamily: 'Gotham',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'choice',
        text: 'Company size?',
        description: '',
        required: true,
        options: ['1-10 employees', '11-50', '51-200', '201-1000', '1000+'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#CC0000',
        fontFamily: 'Gotham',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How important is innovation to your business?',
        description: 'Not important | Somewhat | Critical',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        panelBackgroundColor: '#181B21',
        fontFamily: 'Gotham',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'multiple',
        text: 'What challenges do you face?',
        description: 'Select all that apply',
        required: true,
        options: ['Budget constraints', 'Time limitations', 'Technical skills', 'Market competition', 'Regulations'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#393C41',
        fontFamily: 'Gotham',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Survey Complete',
        description: 'Thank you for your time',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #181B21 0%, #393C41 50%, #CC0000 100%)',
        fontFamily: 'Gotham',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== REGISTRATION & BOOKING =====
  
  // Nike-inspired (Orange/Black/White)
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Register attendees for your event',
    category: 'registration',
    theme: {
      backgroundColor: '#000000',
      textColor: '#FFFFFF',
      primaryColor: '#FA5400',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Join The Event',
        description: 'Register now - Limited spots available',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
        panelBackgroundColor: '#000000',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #2D2D2D 50%, #FA5400 100%)',
        fontFamily: 'Futura',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Full Name',
        description: '',
        required: true,
        placeholder: 'Jane Smith',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#2D2D2D',
        fontFamily: 'Futura',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: "We'll send your ticket here",
        required: true,
        placeholder: 'jane@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#FA5400',
        fontFamily: 'Futura',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'phone',
        text: 'Phone Number',
        description: '',
        required: true,
        placeholder: '+1 555 000 0000',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#000000',
        fontFamily: 'Futura',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Ticket Type',
        description: '',
        required: true,
        options: ['Early Bird - $49', 'Regular - $79', 'VIP - $149', 'Group (4+) - $199'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#2D2D2D',
        fontFamily: 'Futura',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'multiple',
        text: 'Topics of Interest',
        description: 'Select all that apply',
        required: false,
        options: ['Technology', 'Business', 'Design', 'Marketing', 'Leadership'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#FA5400',
        fontFamily: 'Futura',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Just Do It! ✓',
        description: 'Registration confirmed - See you there',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #2D2D2D 50%, #FA5400 100%)',
        fontFamily: 'Futura',
        fontSize: 'xlarge',
      },
    ],
  },

  // Figma-inspired (Multicolor Modern)
  {
    id: 'webinar-registration',
    name: 'Webinar Registration',
    description: 'Sign up attendees for your webinar',
    category: 'registration',
    theme: {
      backgroundColor: '#1E1E1E',
      textColor: '#FFFFFF',
      primaryColor: '#A259FF',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Join Our Live Webinar',
        description: 'Learn from industry experts',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #1E1E1E 0%, #A259FF 50%, #0ACF83 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'First Name',
        description: '',
        required: true,
        placeholder: 'Alex',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#A259FF',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'text',
        text: 'Last Name',
        description: '',
        required: true,
        placeholder: 'Johnson',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#0ACF83',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'email',
        text: 'Work Email',
        description: 'The webinar link will be sent here',
        required: true,
        placeholder: 'alex@company.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#1E1E1E',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Your Role',
        description: '',
        required: true,
        options: ['Designer', 'Developer', 'Product Manager', 'Executive', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        panelBackgroundColor: '#A259FF',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "You're registered! 🎨",
        description: 'Check your email for the webinar link',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #1E1E1E 0%, #A259FF 50%, #0ACF83 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== E-COMMERCE & RETAIL =====
  
  // Shopify-inspired (Green/Teal/Navy)
  {
    id: 'product-inquiry',
    name: 'Product Inquiry',
    description: 'Let customers ask about your products',
    category: 'e-commerce',
    theme: {
      backgroundColor: '#004C3F',
      textColor: '#FFFFFF',
      primaryColor: '#008060',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Product Inquiry',
        description: 'Get answers about our products',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
        panelBackgroundColor: '#004C3F',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #004C3F 0%, #008060 50%, #5C9C92 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'John Merchant',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#008060',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: '',
        required: true,
        placeholder: 'john@store.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        panelBackgroundColor: '#5C9C92',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Which product are you interested in?',
        description: '',
        required: true,
        options: ['Product A', 'Product B', 'Product C', 'Product D', 'Multiple Products'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'What would you like to know?',
        description: '',
        required: true,
        options: ['Pricing', 'Availability', 'Shipping', 'Technical specs', 'Bulk orders', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Additional Details',
        description: '',
        required: false,
        placeholder: 'Tell us more about your inquiry...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you! 🛍️',
        description: "We'll respond within 24 hours",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #004C3F 0%, #008060 50%, #5C9C92 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== HEALTHCARE & WELLNESS =====
  
  // Calm/Headspace-inspired (Soft Blue/Purple/Lavender)
  {
    id: 'health-assessment',
    name: 'Health Assessment',
    description: 'Collect health information from patients',
    category: 'healthcare',
    theme: {
      backgroundColor: '#5B8CE8',
      textColor: '#FFFFFF',
      primaryColor: '#7C9BDA',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Health Assessment',
        description: 'Your wellness journey starts here',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5B8CE8 0%, #7C9BDA 50%, #A8B9E8 100%)',
        fontFamily: 'Circular',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Full Name',
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: "We'll send your results here",
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'What brings you here today?',
        description: '',
        required: true,
        options: ['General checkup', 'Specific concern', 'Follow-up visit', 'Preventive care'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'scale',
        text: 'How would you rate your overall health?',
        description: 'Poor | Fair | Excellent',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Any specific concerns?',
        description: 'Share any health concerns or questions',
        required: false,
        placeholder: 'Tell us more...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Circular',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Assessment Complete 🌟',
        description: "We'll be in touch soon",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5B8CE8 0%, #7C9BDA 50%, #A8B9E8 100%)',
        fontFamily: 'Circular',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== JOB APPLICATIONS =====
  
  // LinkedIn-inspired (Blue/Navy/White)
  {
    id: 'job-application',
    name: 'Job Application',
    description: 'Streamline your hiring process',
    category: 'hr',
    theme: {
      backgroundColor: '#0A66C2',
      textColor: '#FFFFFF',
      primaryColor: '#004182',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Join Our Team',
        description: "We're excited to learn about you",
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
        panelBackgroundColor: '#0A66C2',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0A66C2 0%, #004182 50%, #00365D 100%)',
        fontFamily: 'system-ui',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Full Name',
        description: '',
        required: true,
        placeholder: 'Jane Professional',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: '',
        required: true,
        placeholder: 'jane@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'phone',
        text: 'Phone Number',
        description: '',
        required: true,
        placeholder: '+1 555 000 0000',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Which position are you applying for?',
        description: '',
        required: true,
        options: ['Software Engineer', 'Product Manager', 'Designer', 'Marketing Manager', 'Sales Rep'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'Years of experience?',
        description: '',
        required: true,
        options: ['0-2 years', '3-5 years', '6-10 years', '10+ years'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'q6',
        type: 'long-text',
        text: 'Why do you want to join our team?',
        description: '',
        required: true,
        placeholder: 'Share your motivation...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'system-ui',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Application Received! 💼',
        description: "We'll review your application and be in touch",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0A66C2 0%, #004182 50%, #00365D 100%)',
        fontFamily: 'system-ui',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== EDUCATION =====
  
  // Duolingo-inspired (Green/Yellow/Fun)
  {
    id: 'course-enrollment',
    name: 'Course Enrollment',
    description: 'Enroll students in your courses',
    category: 'education',
    theme: {
      backgroundColor: '#58CC02',
      textColor: '#FFFFFF',
      primaryColor: '#89E219',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Start Learning Today!',
        description: 'Join thousands of students',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #58CC02 0%, #89E219 50%, #FFC800 100%)',
        fontFamily: 'DIN Round',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "Student's Name",
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'DIN Round',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: '',
        required: true,
        placeholder: 'student@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'DIN Round',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Which course interests you?',
        description: '',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced', 'Professional'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'DIN Round',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Learning goal?',
        description: '',
        required: true,
        options: ['Career advancement', 'Personal development', 'Certification', 'Just for fun'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'DIN Round',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'How much time can you dedicate weekly?',
        description: '',
        required: true,
        options: ['1-2 hours', '3-5 hours', '6-10 hours', '10+ hours'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'DIN Round',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "You're enrolled! 🎓",
        description: 'Check your email to get started',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #58CC02 0%, #89E219 50%, #FFC800 100%)',
        fontFamily: 'DIN Round',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== TRAVEL & HOSPITALITY =====
  
  // Booking.com-inspired (Blue/Navy/Cyan)
  {
    id: 'travel-booking',
    name: 'Travel Inquiry',
    description: 'Capture travel booking requests',
    category: 'travel',
    theme: {
      backgroundColor: '#003580',
      textColor: '#FFFFFF',
      primaryColor: '#0071C2',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Plan Your Dream Trip',
        description: "Let's create unforgettable memories",
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80',
        panelBackgroundColor: '#003580',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #003580 0%, #0071C2 50%, #00AAEF 100%)',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'Traveler Name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: "We'll send the itinerary here",
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Destination?',
        description: 'Where would you like to go?',
        required: true,
        options: ['Europe', 'Asia', 'Americas', 'Africa', 'Oceania', 'Not sure yet'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Travel dates',
        description: 'When are you planning to travel?',
        required: true,
        options: ['Next month', 'In 2-3 months', 'In 4-6 months', 'Not decided'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'Budget range',
        description: 'Per person',
        required: true,
        options: ['Under $1,000', '$1,000 - $3,000', '$3,000 - $5,000', '$5,000+'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Bon Voyage! ✈️',
        description: "We'll send you personalized recommendations",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #003580 0%, #0071C2 50%, #00AAEF 100%)',
        fontFamily: 'BlinkMacSystemFont',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== FINANCE & FINTECH =====
  
  // Revolut-inspired (Dark Navy/Electric Blue/Cyan)
  {
    id: 'financial-consultation',
    name: 'Financial Consultation',
    description: 'Book financial advisory sessions',
    category: 'finance',
    theme: {
      backgroundColor: '#0D1B2A',
      textColor: '#FFFFFF',
      primaryColor: '#00D4FF',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Financial Consultation',
        description: 'Get expert advice on your finances',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0D1B2A 0%, #1E3A5F 50%, #00D4FF 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Full Name',
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'What service are you interested in?',
        description: '',
        required: true,
        options: ['Investment planning', 'Retirement planning', 'Tax optimization', 'Wealth management', 'General advice'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Current financial situation',
        description: '',
        required: true,
        options: ['Just starting', 'Some savings', 'Well established', 'High net worth'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Tell us about your goals',
        description: 'What are you trying to achieve?',
        required: false,
        placeholder: 'Share your financial goals...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Request Received! 💰',
        description: "An advisor will contact you within 24 hours",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #0D1B2A 0%, #1E3A5F 50%, #00D4FF 100%)',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== FOOD & BEVERAGE =====
  
  // Uber Eats-inspired (Black/Green/White)
  {
    id: 'restaurant-reservation',
    name: 'Restaurant Reservation',
    description: 'Accept table reservations',
    category: 'food',
    theme: {
      backgroundColor: '#000000',
      textColor: '#FFFFFF',
      primaryColor: '#06C167',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Reserve Your Table',
        description: 'Book your dining experience',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        panelBackgroundColor: '#000000',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #1A1A1A 50%, #06C167 100%)',
        fontFamily: 'Uber Move',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Name for the reservation',
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: "We'll send a confirmation",
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'phone',
        text: 'Phone Number',
        description: 'In case we need to reach you',
        required: true,
        placeholder: '+1 555 000 0000',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Party size',
        description: 'How many people?',
        required: true,
        options: ['2 people', '3-4 people', '5-6 people', '7+ people'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'Preferred time',
        description: '',
        required: true,
        options: ['Lunch (12-3pm)', 'Afternoon (3-6pm)', 'Dinner (6-9pm)', 'Late (9pm+)'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'q6',
        type: 'long-text',
        text: 'Special requests',
        description: 'Dietary restrictions, occasion, etc.',
        required: false,
        placeholder: 'Tell us more...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Uber Move',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Reservation Confirmed! 🍽️',
        description: "We'll see you soon",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #1A1A1A 50%, #06C167 100%)',
        fontFamily: 'Uber Move',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== FITNESS & WELLNESS =====
  
  // Peloton-inspired (Red/Black/White)
  {
    id: 'fitness-assessment',
    name: 'Fitness Assessment',
    description: 'Evaluate client fitness levels',
    category: 'fitness',
    theme: {
      backgroundColor: '#000000',
      textColor: '#FFFFFF',
      primaryColor: '#CB2C30',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Start Your Fitness Journey',
        description: "Let's assess your current level",
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
        panelBackgroundColor: '#000000',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #2D2D2D 50%, #CB2C30 100%)',
        fontFamily: 'Graphik',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'Name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Graphik',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Graphik',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Current fitness level',
        description: '',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced', 'Elite'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Graphik',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Primary goal',
        description: '',
        required: true,
        options: ['Weight loss', 'Build muscle', 'Endurance', 'Flexibility', 'General health'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Graphik',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'scale',
        text: 'How motivated are you? (1-10)',
        description: 'Not motivated | Somewhat | Very motivated',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        fontFamily: 'Graphik',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "Let's Go! 💪",
        description: 'Your personalized plan is ready',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #000000 0%, #2D2D2D 50%, #CB2C30 100%)',
        fontFamily: 'Graphik',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== BEAUTY & COSMETICS =====
  
  // Glossier-inspired (Soft Pink/Peach/Rose)
  {
    id: 'beauty-consultation',
    name: 'Beauty Consultation',
    description: 'Book personalized beauty consultations',
    category: 'beauty',
    theme: {
      backgroundColor: '#FFE5E5',
      textColor: '#3C3C43',
      primaryColor: '#FF3B30',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Your Beauty Journey',
        description: 'Discover your perfect routine',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
        panelBackgroundColor: '#FFE5E5',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FFE5E5 0%, #FFB4AB 50%, #FF8A80 100%)',
        fontFamily: 'Apercu',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'Your name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Apercu',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email Address',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Apercu',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Skin type',
        description: '',
        required: true,
        options: ['Normal', 'Dry', 'Oily', 'Combination', 'Sensitive'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Apercu',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'multiple',
        text: 'Main concerns',
        description: 'Select all that apply',
        required: true,
        options: ['Acne', 'Aging', 'Dark spots', 'Dryness', 'Redness', 'Texture'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Apercu',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'Looking for',
        description: '',
        required: true,
        options: ['Skincare', 'Makeup', 'Both'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Apercu',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Beautiful! ✨',
        description: "We'll send you personalized recommendations",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #FFE5E5 0%, #FFB4AB 50%, #FF8A80 100%)',
        fontFamily: 'Apercu',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== TECH & SaaS =====
  
  // Slack-inspired (Purple/Aubergine/Plum)
  {
    id: 'demo-request',
    name: 'Product Demo Request',
    description: 'Schedule product demonstrations',
    category: 'saas',
    theme: {
      backgroundColor: '#4A154B',
      textColor: '#FFFFFF',
      primaryColor: '#611F69',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Book Your Demo',
        description: 'See how we can help your team',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #4A154B 0%, #611F69 50%, #7B2D7E 100%)',
        fontFamily: 'Lato',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'John Doe',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Work Email',
        description: '',
        required: true,
        placeholder: 'john@company.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'text',
        text: 'Company Name',
        description: '',
        required: true,
        placeholder: 'Acme Corp',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Company size',
        description: '',
        required: true,
        options: ['1-10', '11-50', '51-200', '201-1000', '1000+'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'choice',
        text: 'Your role',
        description: '',
        required: true,
        options: ['Executive', 'Manager', 'Team Lead', 'Individual Contributor'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'q6',
        type: 'long-text',
        text: 'What are you looking to achieve?',
        description: '',
        required: false,
        placeholder: 'Tell us about your goals...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Lato',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Demo Scheduled! 📅',
        description: "We'll send you a calendar invite",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #4A154B 0%, #611F69 50%, #7B2D7E 100%)',
        fontFamily: 'Lato',
        fontSize: 'xlarge',
      },
    ],
  },

  // Asana-inspired (Coral/Pink/Orange)
  {
    id: 'project-brief',
    name: 'Project Brief',
    description: 'Collect project requirements',
    category: 'saas',
    theme: {
      backgroundColor: '#F06A6A',
      textColor: '#FFFFFF',
      primaryColor: '#FC636B',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'New Project Brief',
        description: "Let's bring your vision to life",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #F06A6A 0%, #FC636B 50%, #FFA270 100%)',
        fontFamily: 'Mulish',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Project Name',
        description: '',
        required: true,
        placeholder: 'Enter project name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Mulish',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Your Email',
        description: '',
        required: true,
        placeholder: 'you@company.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Mulish',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Project type',
        description: '',
        required: true,
        options: ['Website', 'Mobile App', 'Software', 'Marketing Campaign', 'Other'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Mulish',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Timeline',
        description: '',
        required: true,
        options: ['Rush (1-2 weeks)', 'Standard (1 month)', 'Flexible (2-3 months)', 'Not urgent'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Mulish',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Project description',
        description: 'Tell us about your project',
        required: true,
        placeholder: 'Describe your vision...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Mulish',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Brief Received! 🚀',
        description: "We'll get back to you soon",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #F06A6A 0%, #FC636B 50%, #FFA270 100%)',
        fontFamily: 'Mulish',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== SOCIAL & COMMUNITY =====
  
  // Discord-inspired (Blurple/Dark/Blue)
  {
    id: 'community-signup',
    name: 'Community Signup',
    description: 'Welcome new community members',
    category: 'community',
    theme: {
      backgroundColor: '#5865F2',
      textColor: '#FFFFFF',
      primaryColor: '#7289DA',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Join Our Community',
        description: 'Connect with like-minded people',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5865F2 0%, #7289DA 50%, #99AAB5 100%)',
        fontFamily: 'Ginto',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Username',
        description: 'How should we call you?',
        required: true,
        placeholder: 'cooluser123',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Ginto',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Ginto',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'multiple',
        text: 'Interests',
        description: 'Select all that apply',
        required: true,
        options: ['Gaming', 'Tech', 'Art', 'Music', 'Sports', 'Coding'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Ginto',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'long-text',
        text: 'Introduce yourself',
        description: 'Tell us a bit about you',
        required: false,
        placeholder: 'Share your story...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Ginto',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Welcome! 🎮',
        description: "You're now part of the community",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #5865F2 0%, #7289DA 50%, #99AAB5 100%)',
        fontFamily: 'Ginto',
        fontSize: 'xlarge',
      },
    ],
  },

  // ===== NONPROFITS & DONATIONS =====
  
  // UNICEF-inspired (Light Blue/Sky/Aqua)
  {
    id: 'volunteer-signup',
    name: 'Volunteer Signup',
    description: 'Recruit volunteers for your cause',
    category: 'nonprofit',
    theme: {
      backgroundColor: '#00AEEF',
      textColor: '#FFFFFF',
      primaryColor: '#0092D1',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Make a Difference',
        description: 'Join our volunteer team',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&q=80',
        panelBackgroundColor: '#00AEEF',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #00AEEF 0%, #0092D1 50%, #007BB5 100%)',
        fontFamily: 'Open Sans',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: 'Your Name',
        description: '',
        required: true,
        placeholder: 'Name',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Open Sans',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: 'Email',
        description: '',
        required: true,
        placeholder: 'you@example.com',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Open Sans',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'multiple',
        text: 'Areas of interest',
        description: 'Select all that apply',
        required: true,
        options: ['Education', 'Healthcare', 'Environment', 'Community', 'Fundraising', 'Events'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Open Sans',
        fontSize: 'large',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Availability',
        description: '',
        required: true,
        options: ['Weekdays', 'Weekends', 'Both', 'Flexible'],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Open Sans',
        fontSize: 'large',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Why do you want to volunteer?',
        description: '',
        required: false,
        placeholder: 'Tell us your motivation...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Open Sans',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank You! 💙',
        description: "We'll be in touch soon",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #00AEEF 0%, #0092D1 50%, #007BB5 100%)',
        fontFamily: 'Open Sans',
        fontSize: 'xlarge',
      },
    ],
  },
];

import { brandedTemplates } from './brandedTemplates';
import { applyThemeColorsToAllTemplates } from './templateUtils';

// Combiner tous les templates
const allTemplatesRaw = [...typeformTemplatesRaw, ...brandedTemplates];

// Appliquer automatiquement les couleurs de texte à tous les templates
export const typeformTemplates = applyThemeColorsToAllTemplates(allTemplatesRaw);

export const getTemplateById = (id: string): TypeformTemplate | undefined => {
  return typeformTemplates.find(template => template.id === id);
};

export const getTemplatesByCategory = (category: string): TypeformTemplate[] => {
  return typeformTemplates.filter(template => template.category === category);
};
