import { TypeformQuestion } from '../components/TypeformPreview';

export interface TypeformTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  questions: TypeformQuestion[];
  theme?: {
    backgroundColor?: string;
    textColor?: string;
    primaryColor?: string;
    fontFamily?: string;
  };
}

export const typeformTemplates: TypeformTemplate[] = [
  {
    id: 'picture-choice-demo',
    name: 'Picture Choice Demo',
    description: 'Beautiful picture choice questions with Typeform-style layout',
    category: 'demo',
    theme: {
      backgroundColor: '#FFF5E6',
      textColor: '#1F2937',
      primaryColor: '#F59E0B',
      fontFamily: 'Inter, sans-serif',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Bienvenue à notre formulaire',
        description: 'Cela ne prendra que quelques minutes',
        required: false,
        layout: 'centered-card',
        fontFamily: 'Inter, sans-serif',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'choice',
        text: 'Your question here. Recall information with @',
        description: 'Description (optional)',
        required: true,
        options: ['A', 'B', 'C'],
        layout: 'cards-grid',
        fontFamily: 'Inter, sans-serif',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Merci pour votre participation !',
        description: 'Vos réponses ont été enregistrées',
        required: false,
        layout: 'centered-card',
      },
    ],
  },
  {
    id: 'customer-feedback',
    name: 'Customer Feedback',
    description: 'Collect valuable feedback from your customers',
    category: 'feedback',
    thumbnail: 'https://images.typeform.com/images/vZe5UPd5c9kN/image/default',
    theme: {
      backgroundColor: '#4E211D',
      textColor: '#FFFFFF',
      primaryColor: '#FDCCC3',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Customer Feedback Survey',
        description: 'Help us improve your experience',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=800&q=80',
        fontFamily: 'Poppins',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "First, what's your name?",
        description: '',
        required: true,
        placeholder: '',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
        fontFamily: 'Poppins',
        fontSize: 'large',
        subFields: [
          {
            id: 'firstName',
            label: 'First name',
            placeholder: 'Jane',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'lastName',
            label: 'Last name',
            placeholder: 'Doe',
            type: 'text',
            required: true,
            width: 'half',
          },
        ],
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email address?",
        description: "We'll use this to send you a copy of your responses",
        required: true,
        placeholder: 'name@example.com',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=800',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How satisfied are you with our product?',
        description: 'Be honest 😊 | Somewhat satisfied | Very satisfied',
        required: true,
        min: 0,
        max: 10,
        layout: 'scale-horizontal',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'How likely are you to recommend us to a friend?',
        description: 'Choose one option',
        required: true,
        options: ['Very unlikely', 'Unlikely', 'Neutral', 'Likely', 'Very likely'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'What can we do to improve?',
        description: 'Your feedback helps us get better',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you for your feedback! 🎉',
        description: 'Your responses help us serve you better',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Poppins',
        fontSize: 'xlarge',
      },
    ],
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Simple and elegant contact form',
    category: 'contact',
    thumbnail: 'https://images.unsplash.com/photo-1525182008055-f88b95ff7980?w=800&q=80',
    theme: {
      backgroundColor: '#1a1a2e',
      textColor: '#FFFFFF',
      primaryColor: '#16213e',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Get in Touch',
        description: "We'd love to hear from you",
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        subFields: [
          {
            id: 'firstName',
            label: 'First name',
            placeholder: 'John',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'lastName',
            label: 'Last name',
            placeholder: 'Doe',
            type: 'text',
            required: true,
            width: 'half',
          },
        ],
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: '',
        required: true,
        placeholder: 'john@example.com',
        layout: 'fullwidth-input',
      },
      {
        id: 'q3',
        type: 'phone',
        text: "What's your phone number?",
        description: 'Optional',
        required: false,
        placeholder: '+1 234 567 8900',
        layout: 'fullwidth-input',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'What can we help you with?',
        description: 'Choose the topic that best describes your inquiry',
        required: true,
        options: ['Sales', 'Support', 'Partnership', 'Other'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Tell us more about your inquiry',
        description: '',
        required: true,
        placeholder: 'Describe your needs...',
        layout: 'fullwidth-input',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "We'll be in touch soon! ✉️",
        description: 'Thank you for contacting us',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },
  {
    id: 'product-survey',
    name: 'Product Survey',
    description: 'Gather insights about your product',
    category: 'survey',
    thumbnail: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    theme: {
      backgroundColor: '#f8f9fa',
      textColor: '#212529',
      primaryColor: '#841b60',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Product Survey',
        description: 'Share your experience with us',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'choice',
        text: 'Which product did you purchase?',
        description: 'Select one',
        required: true,
        options: ['Product A', 'Product B', 'Product C', 'Product D'],
        layout: 'cards-grid',
      },
      {
        id: 'q2',
        type: 'scale',
        text: 'How would you rate the quality?',
        description: 'Poor | Average | Excellent',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How would you rate the value for money?',
        description: 'Poor value | Fair value | Great value',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q4',
        type: 'multiple',
        text: 'What features do you use the most?',
        description: 'Select all that apply',
        required: false,
        options: ['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Any additional comments?',
        description: 'Optional',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you for your time! 🙏',
        description: 'Your feedback is valuable to us',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // Event Registration
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Register attendees for your event',
    category: 'business',
    thumbnail: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
    theme: {
      backgroundColor: '#ffffff',
      textColor: '#000000',
      primaryColor: '#841b60',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Event Registration',
        description: 'Secure your spot today',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'text',
        text: "What's your full name?",
        description: '',
        required: true,
        placeholder: '',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
        subFields: [
          {
            id: 'firstName',
            label: 'First name',
            placeholder: 'Jane',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'lastName',
            label: 'Last name',
            placeholder: 'Smith',
            type: 'text',
            required: true,
            width: 'half',
          },
        ],
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: "We'll send your ticket here",
        required: true,
        placeholder: 'jane@example.com',
        layout: 'fullwidth-input',
      },
      {
        id: 'q3',
        type: 'phone',
        text: "What's your phone number?",
        description: 'In case we need to reach you',
        required: true,
        placeholder: '+1 234 567 8900',
        layout: 'fullwidth-input',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Which ticket type would you like?',
        description: 'Choose your ticket',
        required: true,
        options: ['Early Bird', 'Regular', 'VIP', 'Group (4+)'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'multiple',
        text: 'What topics interest you most?',
        description: 'Select all that apply',
        required: false,
        options: ['Technology', 'Business', 'Design', 'Marketing'],
        layout: 'cards-grid',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'See you at the event! 🎉',
        description: 'Check your email for confirmation',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },

  // Employer Feedback
  {
    id: 'employer-feedback',
    name: 'Employer Feedback Form',
    description: 'Formulaire de feedback employeur avec design moderne',
    category: 'business',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop',
    theme: {
      backgroundColor: '#372F15',
      textColor: '#FFFFFF',
      primaryColor: '#EDDE7D',
      fontFamily: 'Apercu Pro',
    },
    questions: [
      {
        id: 'welcome-employer',
        type: 'welcome',
        text: 'How are we doing?',
        description: 'Your feedback helps us build an even better place to work.',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image-card',
        imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop',
        fontFamily: 'Apercu Pro',
        fontSize: 'xlarge',
      },
      {
        id: 'q1-employer',
        type: 'text',
        text: 'What is your name?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        subFields: [
          {
            id: 'firstName',
            label: 'First name',
            placeholder: 'John',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'lastName',
            label: 'Last name',
            placeholder: 'Doe',
            type: 'text',
            required: true,
            width: 'half',
          },
        ],
      },
      {
        id: 'q2-employer',
        type: 'email',
        text: 'What is your email address?',
        description: '',
        required: true,
        placeholder: 'john@example.com',
        layout: 'centered-card',
      },
      {
        id: 'q3-employer',
        type: 'scale',
        text: 'How satisfied are you with your current role?',
        description: 'Not satisfied | | Very satisfied',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q4-employer',
        type: 'scale',
        text: 'How would you rate the work environment?',
        description: 'Poor | | Excellent',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q5-employer',
        type: 'long-text',
        text: 'What improvements would you suggest?',
        description: 'Optional',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
      },
      {
        id: 'thankyou-employer',
        type: 'thankyou',
        text: 'Thank you for your feedback!',
        description: 'Your input helps us create a better workplace.',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Apercu Pro',
        fontSize: 'xlarge',
      },
    ],
  },

  {
    id: 'ces',
    name: 'Customer Effort Score (CES)',
    description: 'Measure how easy it is for customers to interact with your product',
    category: 'feedback',
    thumbnail: 'https://images.typeform.com/images/t6nURrZ6Wmup/image/default',
    theme: {
      backgroundColor: '#8B7BA8',
      textColor: '#FFFFFF',
      primaryColor: '#E7F4FD',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'How did we do?',
        description: 'press Enter ↵',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image-card',
        imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'scale',
        text: 'How easy was it to resolve your issue today?',
        description: 'Very difficult | | Very easy',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q2',
        type: 'choice',
        text: 'What was the primary reason for your score?',
        description: 'Select the option that best describes your experience',
        required: true,
        options: [
          'The process was too complicated',
          'I had technical difficulties',
          'I couldn\'t find what I needed',
          'Everything worked smoothly',
          'Other',
        ],
        layout: 'cards-grid',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'long-text',
        text: 'Is there anything else you\'d like to share about your experience?',
        description: 'Your feedback helps us improve',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Thank you for your feedback! 💜',
        description: 'Your input helps us improve',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
    ],
  },
  {
    id: 'lead-generation',
    name: 'Lead Generation Form',
    description: 'Professional lead generation form with multi-field inputs and international phone support',
    category: 'contact',
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    theme: {
      backgroundColor: '#3C3215',
      textColor: '#F5E6C4',
      primaryColor: '#F2CF4A',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'How can we support your business?',
        description: 'Our team of experts are ready to help.',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'xlarge',
        ctaLabel: 'Submit inquiry',
        navVariant: 'pill-label',
        buttonStyle: 'solid',
      },
      {
        id: 'q1',
        type: 'text',
        text: "Before we get started, what's your full name?",
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        ctaLabel: 'OK',
        navVariant: 'pill-label',
        buttonStyle: 'solid',
        subFields: [
          {
            id: 'firstName',
            label: 'First name',
            placeholder: 'Jane',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'lastName',
            label: 'Last name',
            placeholder: 'Smith',
            type: 'text',
            required: true,
            width: 'half',
          },
        ],
      },
      {
        id: 'q2',
        type: 'multiple',
        text: 'Which services do you need?',
        description: 'Choose as many as you like',
        required: true,
        options: ['Contracts', 'Real estate', 'Taxes', 'HR'],
        optionImages: [
          'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
          'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
          'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
          'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
        ],
        layout: 'cards-grid',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        ctaLabel: 'OK',
        navVariant: 'pill-label',
        buttonStyle: 'solid',
      },
      {
        id: 'q3',
        type: 'choice',
        text: 'Which support plan would you like?',
        description: 'We can create a custom offer for you.',
        required: true,
        options: ['Monthly retainer', 'On demand'],
        layout: 'cards-grid',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        ctaLabel: 'OK',
        navVariant: 'pill-label',
        buttonStyle: 'solid',
      },
      {
        id: 'q4',
        type: 'phone',
        text: "Before you go, what's your phone number?",
        description: 'Someone from our team will contact you.',
        required: true,
        placeholder: '(201) 555-0123',
        layout: 'fullwidth-input',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'large',
        ctaLabel: 'Submit',
        navVariant: 'pill-label',
        buttonStyle: 'solid',
        phoneCountry: {
          code: 'US',
          label: 'United States',
          flag: '🇺🇸',
          dialCode: '+1',
        },
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: "Thanks, we'll get back to you shortly.",
        description: 'We appreciate your interest in our services',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Cormorant Garamond',
        fontSize: 'xlarge',
      },
    ],
  },
  {
    id: 'figaro-etudiant-orientation',
    name: 'Le Figaro Etudiant - Orientation',
    description: 'Formulaire d\'orientation scolaire pour étudiants',
    category: 'education',
    thumbnail: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    theme: {
      backgroundColor: '#F7F8F9',
      textColor: '#20375D',
      primaryColor: '#F15C41',
      fontFamily: 'Source Sans Pro',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'Le Figaro Etudiant t\'aide à trouver ton école et ta formation',
        description: 'Réponds à quelques questions pour être mis en contact avec les établissements qui correspondent à ton profil',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Source Sans Pro',
        fontSize: 'large',
      },
      {
        id: 'q1-profile',
        type: 'choice',
        text: 'Quel est ton profil ?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'cards-grid',
        options: ['Collégien', 'Lycéen', 'Étudiant', 'Parent'],
        customStyles: {
          // Dimensions exactes des cartes de choix (d'après le HTML original)
          optionCardWidth: '180px',
          optionCardHeight: 'auto',
          optionCardBorderRadius: '8px',
          optionCardBorder: '1px solid #E5E7EB',
          optionCardPadding: '24px 16px',
          optionCardGap: '16px',
          optionCardHoverBg: '#F9FAFB',
          optionCardSelectedBg: '#F15C41',
          optionCardSelectedBorder: '2px solid #F15C41',
          // Texte dans les options
          optionTextSize: '16px',
          optionTextWeight: '500',
          optionTextColor: '#20375D',
          // Boutons
          buttonBorderRadius: '24px',
          buttonPadding: '12px 32px',
          buttonFontSize: '16px',
          buttonFontWeight: '600',
          // Header personnalisé
          showCustomHeader: true,
          headerLogoUrl: 'https://etudiant.lefigaro.fr/images/logo-figaro-etudiant.svg',
          headerTitle: 'Le Figaro Etudiant t\'aide à trouver ton école et ta formation',
          headerBgColor: '#FFFFFF',
          // Footer personnalisé
          showCustomFooter: true,
          footerItems: [
            {
              title: 'Fais le bon choix pour ton avenir',
              description: '',
            },
            {
              title: 'Manifeste ta motivation auprès des écoles',
              description: '',
            },
            {
              title: 'Fais-toi contacter par les écoles qui te correspondent',
              description: '',
            },
          ],
          footerBgColor: '#FFFFFF',
        },
        conditionalLogic: [
          {
            field: 'q1-profile',
            operator: 'equals',
            value: 'Collégien',
            action: 'jump',
            target: 'q2-level-college',
          },
          {
            field: 'q1-profile',
            operator: 'equals',
            value: 'Lycéen',
            action: 'jump',
            target: 'q2-level-lycee',
          },
          {
            field: 'q1-profile',
            operator: 'equals',
            value: 'Étudiant',
            action: 'jump',
            target: 'q2-level-etudiant',
          },
          {
            field: 'q1-profile',
            operator: 'equals',
            value: 'Parent',
            action: 'jump',
            target: 'q3-domains',
          },
        ],
      },
      {
        id: 'q2-level-college',
        type: 'choice',
        text: 'En quelle classe es-tu ?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        options: ['Sixième', 'Cinquième', 'Quatrième', 'Troisième'],
      },
      {
        id: 'q2-level-lycee',
        type: 'choice',
        text: 'En quelle classe es-tu ?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        options: ['Seconde', 'Première', 'Terminale'],
      },
      {
        id: 'q2-level-etudiant',
        type: 'choice',
        text: 'Quel est ton niveau d\'études ?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        options: ['Bac+1', 'Bac+2', 'Bac+3', 'Bac+4', 'Bac+5', 'Bac+6 et plus'],
      },
      {
        id: 'q3-domains',
        type: 'choice',
        text: 'Choisis les domaines qui t\'intéressent',
        description: 'Tape les premières lettres des domaines concernés',
        required: true,
        placeholder: 'Arts / Architecture / Industrie...',
        layout: 'cards-grid',
        options: [
          'Commerce',
          'Médical',
          'Marketing & Marketing digital',
          'Informatique',
          'Management & entrepreneuriat',
          'Restauration - Arts culinaires',
          'Cinéma, Photo',
          'Communication & Communication digitale',
          'Digital',
        ],
      },
      {
        id: 'q4-apprenticeship',
        type: 'choice',
        text: 'Souhaites-tu faire de l\'alternance ?',
        description: '',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        options: ['Oui', 'Non', 'Ne sais pas'],
      },
      {
        id: 'q5-contact-intro',
        type: 'welcome',
        text: 'Plus que quelques infos et on pourra te mettre en relation avec des écoles intéressées par ton profil !',
        description: '',
        required: false,
        placeholder: '',
        layout: 'centered-card',
      },
      {
        id: 'q6-contact-form',
        type: 'form',
        text: 'Tes coordonnées',
        description: 'J\'accepte d\'être contacté(e) par téléphone par notre partenaire Diplomeo pour bénéficier d\'un accompagnement dans mon projet d\'orientation.',
        required: true,
        placeholder: '',
        layout: 'fullwidth-input',
        phoneCountry: {
          code: 'FR',
          label: 'France',
          flag: '🇫🇷',
          dialCode: '+33',
        },
        subFields: [
          {
            id: 'lastName',
            label: 'Nom',
            title: 'Nom*',
            placeholder: 'Nom',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'firstName',
            label: 'Prénom',
            placeholder: 'Prénom',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            id: 'email',
            label: 'Email',
            title: 'Email*',
            placeholder: 'ton.email@exemple.fr',
            type: 'email',
            required: true,
            width: 'full',
          },
          {
            id: 'city',
            label: 'Ville',
            title: 'Ville*',
            placeholder: 'Ville ou code postal',
            type: 'text',
            required: true,
            width: 'full',
          },
          {
            id: 'phone',
            label: 'Téléphone',
            title: 'Téléphone*',
            placeholder: 'Ton n° de téléphone',
            type: 'phone',
            required: true,
            width: 'full',
          },
        ],
      },
      {
        id: 'thankyou',
        type: 'thankyou',
        text: 'Merci pour ton inscription !',
        description: 'Les établissements correspondant à ton profil vont te contacter prochainement.',
        required: false,
        placeholder: '',
        layout: 'centered-card',
        fontFamily: 'Source Sans Pro',
        fontSize: 'large',
      },
    ],
  },
];

export const getTemplateById = (id: string): TypeformTemplate | undefined => {
  return typeformTemplates.find(template => template.id === id);
};

export const getTemplatesByCategory = (category: string): TypeformTemplate[] => {
  return typeformTemplates.filter(template => template.category === category);
};
