import { TypeformQuestion } from '../components/TypeformPreview';

export interface TypeformTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  thumbnail?: string;
  questions: TypeformQuestion[];
  theme?: {
    backgroundColor?: string;
    textColor?: string;
    primaryColor?: string;
  };
}

export const typeformTemplates: TypeformTemplate[] = [
  {
    id: 'customer-feedback',
    name: 'Customer Feedback',
    description: 'Collect valuable feedback from your customers',
    category: 'feedback',
    thumbnail: 'https://images.typeform.com/images/vZe5UPd5c9kN/image/default',
    theme: {
      backgroundColor: '#4E211D',
      textColor: '#FFFFFF',
      primaryColor: '#FDCCC3',
    },
    questions: [
      {
        id: 'q1',
        type: 'text',
        text: "First, what's your name?",
        description: '',
        required: true,
        placeholder: 'Jane',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
        panelBackgroundColor: '#4E211D',
        backgroundType: 'image',
        backgroundImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1920&q=80',
        backgroundOverlayOpacity: 0.3,
        backgroundOverlayColor: '#4E211D',
        fontFamily: 'Poppins',
        fontSize: 'large',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email address?",
        description: "We'll use this to send you a copy of your responses",
        required: true,
        placeholder: 'name@example.com',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=800',
        panelBackgroundColor: '#4E211D',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How satisfied are you with our product?',
        description: 'Be honest 😊 | Somewhat satisfied | Very satisfied',
        required: true,
        min: 0,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'gradient',
        backgroundGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        fontFamily: 'Montserrat',
        fontSize: 'xlarge',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'How likely are you to recommend us to a friend?',
        description: 'Choose one option',
        required: true,
        options: ['Very unlikely', 'Unlikely', 'Neutral', 'Likely', 'Very likely'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'What can we do to improve?',
        description: 'Your feedback helps us get better',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
      },
    ],
  },
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'Simple and elegant contact form',
    category: 'contact',
    theme: {
      backgroundColor: '#1a1a2e',
      textColor: '#FFFFFF',
      primaryColor: '#16213e',
    },
    questions: [
      {
        id: 'q1',
        type: 'text',
        text: "What's your name?",
        description: '',
        required: true,
        placeholder: 'John Doe',
        layout: 'fullwidth-input',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: '',
        required: true,
        placeholder: 'john@example.com',
        layout: 'fullwidth-input',
      },
      {
        id: 'q3',
        type: 'phone',
        text: "What's your phone number?",
        description: 'Optional',
        required: false,
        placeholder: '+1 234 567 8900',
        layout: 'fullwidth-input',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'What can we help you with?',
        description: 'Choose the topic that best describes your inquiry',
        required: true,
        options: ['Sales', 'Support', 'Partnership', 'Other'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Tell us more about your inquiry',
        description: '',
        required: true,
        placeholder: 'Describe your needs...',
        layout: 'fullwidth-input',
      },
    ],
  },
  {
    id: 'product-survey',
    name: 'Product Survey',
    description: 'Gather insights about your product',
    category: 'survey',
    theme: {
      backgroundColor: '#f8f9fa',
      textColor: '#212529',
      primaryColor: '#841b60',
    },
    questions: [
      {
        id: 'q1',
        type: 'choice',
        text: 'Which product did you purchase?',
        description: 'Select one',
        required: true,
        options: ['Product A', 'Product B', 'Product C', 'Product D'],
        layout: 'cards-grid',
      },
      {
        id: 'q2',
        type: 'scale',
        text: 'How would you rate the quality?',
        description: 'Poor | Average | Excellent',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q3',
        type: 'scale',
        text: 'How would you rate the value for money?',
        description: 'Poor value | Fair value | Great value',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
      },
      {
        id: 'q4',
        type: 'multiple',
        text: 'What features do you use the most?',
        description: 'Select all that apply',
        required: false,
        options: ['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'long-text',
        text: 'Any additional comments?',
        description: 'Optional',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
      },
    ],
  },
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Register attendees for your event',
    category: 'registration',
    theme: {
      backgroundColor: '#667eea',
      textColor: '#FFFFFF',
      primaryColor: '#764ba2',
    },
    questions: [
      {
        id: 'q1',
        type: 'text',
        text: "What's your full name?",
        description: '',
        required: true,
        placeholder: 'Jane Smith',
        layout: 'split-left-image-right-text',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
        panelBackgroundColor: '#667eea',
      },
      {
        id: 'q2',
        type: 'email',
        text: "What's your email?",
        description: "We'll send your ticket here",
        required: true,
        placeholder: 'jane@example.com',
        layout: 'fullwidth-input',
      },
      {
        id: 'q3',
        type: 'phone',
        text: "What's your phone number?",
        description: 'In case we need to reach you',
        required: true,
        placeholder: '+1 234 567 8900',
        layout: 'fullwidth-input',
      },
      {
        id: 'q4',
        type: 'choice',
        text: 'Which ticket type would you like?',
        description: 'Choose your ticket',
        required: true,
        options: ['Early Bird', 'Regular', 'VIP', 'Group (4+)'],
        layout: 'cards-grid',
      },
      {
        id: 'q5',
        type: 'multiple',
        text: 'What topics interest you most?',
        description: 'Select all that apply',
        required: false,
        options: ['Technology', 'Business', 'Design', 'Marketing'],
        layout: 'cards-grid',
      },
    ],
  },
  {
    id: 'customer-effort-score',
    name: 'Customer Effort Score (CES)',
    description: 'Measure how easy it is for customers to interact with your company',
    category: 'feedback',
    thumbnail: 'https://images.typeform.com/images/t6nURrZ6Wmup/image/default',
    theme: {
      backgroundColor: '#8B7BA8',
      textColor: '#FFFFFF',
      primaryColor: '#E7F4FD',
    },
    questions: [
      {
        id: 'welcome',
        type: 'welcome',
        text: 'How did we do?',
        description: 'press Enter ↵',
        required: false,
        placeholder: '',
        layout: 'split-left-text-right-image',
        imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
        panelBackgroundColor: '#8B7BA8',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q1',
        type: 'scale',
        text: 'How easy was it to resolve your issue today?',
        description: 'Very difficult | | Very easy',
        required: true,
        min: 1,
        max: 10,
        layout: 'scale-horizontal',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'xlarge',
      },
      {
        id: 'q2',
        type: 'choice',
        text: 'What was the primary reason for your score?',
        description: 'Select the option that best describes your experience',
        required: true,
        options: [
          'The process was too complicated',
          'I had technical difficulties',
          'I couldn\'t find what I needed',
          'Everything worked smoothly',
          'Other',
        ],
        layout: 'cards-grid',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
      {
        id: 'q3',
        type: 'long-text',
        text: 'Is there anything else you\'d like to share about your experience?',
        description: 'Your feedback helps us improve',
        required: false,
        placeholder: 'Share your thoughts...',
        layout: 'fullwidth-input',
        backgroundType: 'color',
        fontFamily: 'Inter',
        fontSize: 'large',
      },
    ],
  },
];

export const getTemplateById = (id: string): TypeformTemplate | undefined => {
  return typeformTemplates.find(template => template.id === id);
};

export const getTemplatesByCategory = (category: string): TypeformTemplate[] => {
  return typeformTemplates.filter(template => template.category === category);
};
