// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmkwascgjntopgkbmctv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZta3dhc2Nnam50b3Bna2JtY3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDA3MzYsImV4cCI6MjA2NjYxNjczNn0.W17ac2AbL4zpsYcLyvPM7QBgFb_vqJvf3QxB0V1ePKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);